# deployer/deployment.yaml
# project_id: # enter valid project_id or leave empty if you pass in to main
project_id:
region: eu-west1
service_source_path: dataflow/devflow/
service_director_service_name: servicedirector
# default_docker_registry:  # if empty this will be created from project_id
default_docker_registry:

cloud_run_defaults:
  cpu: 1000m # 1 vCPU
  memory: 512Mi
  concurrency: 80
  timeout_seconds: 300
  max_instances: 10
  min_instances: 0
  invoker_all: false # Default to private (requires IAM for access)
  env_vars:
    GLOBAL_APP_NAME: "orchestrator-test"
    ENVIRONMENT: "dev"

services:
  servicedirector:
    dockerfile_path: servicedirector/Dockerfile # Path relative to services_source_base_path
    cloud_run_spec:
      ## leave empty and an appropriate one will be created
      ##service_account: servicedirector-sa # Service account name (orchestrator will ensure its existence)
      cpu: 500m # Override default CPU for this service
      memory: 256Mi # Override default memory for this service
      max_instances: 2
      min_instances: 1 #servicedirector should run continuously
      invoker_all: true # Make Service Director publicly accessible for other services to call
      env_vars:
        DIRECTOR_LOG_LEVEL: "info"
  ingestor:
    dockerfile_path: ingestor/Dockerfile # Path relative to services_source_base_path
    cloud_run_spec:
      ## leave empty and an appropriate one will be created
      ## service_account: ingestor-sa # Service account name (orchestrator will ensure its existence)
      max_instances: 4
      min_instances: 1 #ingestor should run continuously
      env_vars:
        ## we will add SERVICE_DIRECTOR_URL after servicedirector deployment
        ##SERVICE_DIRECTOR_URL: "input-topic"
